lanaguage: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yoshmatsumoto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yoshmatsumoto/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-331102144433"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
