lanaguage: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yoshmatsumoto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yoshmatsumoto/docker-react npm run test
